Newtwo
CrowdDotDev/crowd.dev pull request #1027
Opened 2023-06-26 03:42 UTC by Bharaththop

# Resolved compilation error

### What
server port listening error   ,fixed  through simple change

## Checklist ✅
-  New backend functionality has been unit-tested.

2023-06-26 03:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1027) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1027) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CrowdDotDev/crowd.dev?pullRequest=1027) it.</sub>

2023-06-27 10:46 UTC, joanreyero commented
Hey @Bharaththop! Thanks for the pull request. What was the error that caused you to open this?

2023-06-27 13:22 UTC, Bharaththop commented
> Hey @Bharaththop! Thanks for the pull request. What was the error that caused you to open this?

Yeah, If we go through the flow of commits which I raised for the pull request :
1.  Added variables to Docker files which are necessary for the image to run.
2. And in this file  [(scripts/scaffold/nginx/templates/default.conf.template)](url) changed  script as compiler not recognising ssl certificate .

2023-07-07 06:42 UTC, themarolt requested changes

2023-07-07 06:42 UTC, themarolt commented on backend/src/database/Dockerfile.flyway.repair
> +COPY .flyway_repair.sh /repair.sh
this is not gonna work - there is no `.flyway_repair.sh` file

2023-07-07 06:42 UTC, themarolt commented on backend/tsconfi.json
> +    "resolveJsonModule": true,
We already have a `tsconfig.json` in our backend folder - and this is also a `tsconfi.json` without a `g` so it won't be used anyway.

2023-07-07 06:42 UTC, themarolt commented on scripts/scaffold/db/Dockerfile
> +ENV POSTGRES_PASSWORD = 'example'
We are starting things without `scripts/cli` bash script which actually starts this database using docker compose file `scripts/scaffold.yaml` which has all the necessary env. variables set.

2025-04-30 09:05 UTC, closed without merging