Update README.md
CrowdDotDev/crowd.dev pull request #1718
Opened 2023-10-17 18:50 UTC by PentesterPriyanshu

Some sentences earlier were less readable and had small grammatical errors. I have corrected all of that and made the readme file very readable for all users.

# Changes proposed ✍️

### What
- Updated the README file for improved readability and grammar.

### Why
- To ensure better comprehension and clarity for all users.

### How
- Made necessary changes to sentence structures and grammar errors in the README file.

## Checklist ✅
- [x] Label appropriately with `Documentation`.
- [ ] Add screenshots to the PR description for relevant changes.
- [ ] New backend functionality has been unit-tested.
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.

2023-10-17 18:54 UTC, PentesterPriyanshu commented
@joanagmaia  merge this request i have seen some errors so kindly merge it as i am also working on other issues also but some errors i have just encountered while reading some are making sentences confusing

2023-10-17 19:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1718) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1718) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CrowdDotDev/crowd.dev?pullRequest=1718) it.</sub>

2023-10-23 21:45 UTC, PentesterPriyanshu commented
you can review it close it if not required i am already working on another issue

2023-10-26 10:11 UTC, joanagmaia requested changes

2023-10-26 10:11 UTC, joanagmaia commented on README.md
> +Crowd.dev is the Developer Data Platform(DDP) that allows companies to centralize all touch points developers have with their product and brand, whether in the community (e.g., Stack Overflow or Redd
Could you keep Crowd.dev as crowd.dev?

2023-10-26 10:11 UTC, joanagmaia commented on README.md
> +Crowd.dev is open-source, built with developers in mind, available for both hosted and self-hosted deployments, open to extensions, and offers full control over your data.
Could you keep Crowd.dev as crowd.dev?

2023-10-26 10:46 UTC, PentesterPriyanshu commented on README.md
> +Crowd.dev is open-source, built with developers in mind, available for both hosted and self-hosted deployments, open to extensions, and offers full control over your data.
yes i am sorry yes i will keep that , i missed that crowd.dev is the origninal name of website

2023-10-26 11:34 UTC, PentesterPriyanshu commented
@joanagmaia  if you want hover badges  i can also add that it will look like that
![Screenshot 2023-10-26 at 17-03-02 Editing crowd dev_README md at patch-3 · PentesterPriyanshu_crowd dev](https://github.com/CrowdDotDev/crowd.dev/assets/98478305/9ae004d8-06a0-4339-8e75-55f75ffce8ad)

2023-10-30 12:50 UTC, joanagmaia commented
@PentesterPriyanshu it all looks good to me. Could you fix the conflicts once again?
There have been a lot of contributions to README file

2023-10-30 13:26 UTC, PentesterPriyanshu commented
@joanagmaia    now merge this otherwise we will face conflicts

2023-10-30 14:03 UTC, joanagmaia approved these changes

2023-10-30 14:03 UTC, merged