fix(grammatical): correct typos and improve grammar
CrowdDotDev/crowd.dev pull request #1719
Opened 2023-10-18 02:28 UTC by iamahens

This pull request addresses and corrects grammatical and spelling errors throughout the codebase to improve code readability.
The changes include fixing typos, punctuation, and ensuring proper sentence structure without introducing functional modifications.
These updates are intended to enhance the quality of documentation and code comments.
The focus is on making the codebase more polished and user-friendly by eliminating language-related issues.

2023-10-18 02:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1719) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/CrowdDotDev/crowd.dev?pullRequest=1719) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/CrowdDotDev/crowd.dev?pullRequest=1719) it.</sub>

2023-10-18 06:23 UTC, iamahens commented
/check-cla

2023-10-20 05:08 UTC, iamahens commented
please review @jonathimer

2023-10-26 09:49 UTC, joanagmaia requested changes
Hey 👋 
Left some comments 😄

2023-10-26 09:49 UTC, joanagmaia commented on README.md
> +  <h2 align="center">Effortlessly centralize community, product, and customer data.</h2>
Since it's a title it shouldn't have a `.` full stop. Could you remove it?

2023-10-26 09:49 UTC, joanagmaia commented on README.md
> +crowd.dev is the developer data platform (DDP) that lets companies centralize all touch points developers have with their product and brand, be it in community (e.g. Stack Overflow or Reddit), produc
`and their position they stand in their personal custom journey` seems a but confusing.
Could you leave this last past of the sentence as it was?
`where they stand in their personal customer journey`

2023-10-28 10:57 UTC, iamahens commented on README.md
> +crowd.dev is the developer data platform (DDP) that lets companies centralize all touch points developers have with their product and brand, be it in community (e.g. Stack Overflow or Reddit), produc
@joanagmaia Thank you for your review. I have made the changes that you have requested. please check.

2023-10-30 12:49 UTC, joanagmaia approved these changes
LGTM!
Could you fix conflicts with main so that I can merge? Thanks

2023-10-30 12:49 UTC, joanagmaia commented on frontend/src/modules/integration/components/integration-list-page.vue
> +        >Open an issue </a>
Could you remove this extra space?

2025-04-30 09:07 UTC, closed without merging