Feature/dashboard
CrowdDotDev/crowd.dev pull request #77
Opened 2022-10-19 09:46 UTC by gaspergrom

# Changes proposed ✍️
- dashboard redesign and restructure
- added to widget-cube handling if no data so chart display also 0 values
- created component for loading placeholder
- created component to handle cube rendering
- added property to charts to pass context in order to apply advanced chart styling
- restructured activity to have platform specific components
- fixed issues with avatar
- added tailwind config viewer
- added query endpoint to organization and conversation service

- Add the following files to the `dashboard` frontend module:
  - `dashboard-activities-channel.vue`
  - `dashboard-activities-content.vue`
  - `dashboard-activities-count.vue`
  - `dashboard-activities-item.vue`
  - `dashboard-activities-list.vue`
  - `dashboard-activities-message.vue`
  - `dashboard-activities-sentiment.vue`
  - `activities-devto-channel.vue`
  - `activities-devto-content.vue`
  - `activities-devto-message.vue`
  - `activities-discord-channel.vue`
  - `activities-discord-content.vue`
  - `activities-discord-message.vue`
  - `activities-github-channel.vue`
  - `activities-github-message.vue`
  - `activities-slack-channel.vue`
  - `activities-slack-message.vue`
  - `dashboard-conversations-item.vue`
  - `dashboard-conversations-list.vue`
  - `dashboard-conversations-reply.vue`
  - `dashboard-active-integrations.vue`
  - `dashboard-activities.vue`
  - `dashboard-count.vue`
  - `dashboard-filters.vue`
  - `dashboard-header.vue`
  - `dashboard-members.vue`
  - `dashboard-organizations.vue`
  - `dashboard-members-item.vue`
  - `dashboard-organizations-item.vue`
  - `dashboard-badge.vue`
  - `dashboard-page.vue`
  - `dashboard.cube.js

- ### Screenshots
![image](https://user-images.githubusercontent.com/15195228/196653463-651f563e-905a-484a-ad22-96b3cc88cf17.png)
![image](https://user-images.githubusercontent.com/15195228/196653723-c5f75f61-5f78-41af-a147-f213ab1dfeb9.png)
![image](https://user-images.githubusercontent.com/15195228/196653792-7bdee0c4-8ea8-47ed-9f71-0890bb932f7c.png)
![image](https://user-images.githubusercontent.com/15195228/196653843-70423dd7-242b-4b04-a242-5cd3f0186487.png)

        
## Checklist ✅
- [x] Label appropriately with `type:feature 🚀`, `type:enhancement ✨`, `type:bug 🐞`, or `type:documentation 📜`.
- [ ] Tests are passing.  
- [ ] New backend functionality has been unit-tested.
- [ ] Environment variables have been updated
  - [ ] Front-end: `frontend/.env.dist`
  - [ ] Backend: `backend/.env.dist`, `backend/.env.dist.staging`, `backend/.env.dist.staging`.
  - [ ] [Configuration docs](https://docs.crowd.dev/docs/configuration) have been updated.
  - [ ] Team members only: update environment variables in Password manager and update the team
- [ ] API documentation has been updated (if necessary) (see [docs on API documentation](https://docs.crowd.dev/docs/updating-api-documentation)).  
- [ ] [Quality standards](https://github.com/CrowdDotDev/crowd-github-test-public/blob/main/CONTRIBUTING.md#quality-standards) are met.  
- [ ] All changes have been tested in a staging site.  
- [x] All changes are working locally running crowd.dev's Docker local environment.

2022-10-19 13:33 UTC, mariobalca requested changes
Great work @gaspergrom 🙌 this is looking really really good

The one thing that I've noticed (apart from small typos which are not merge-blockers) would be that we shouldn't use `activity.attributes.url` (for example), since we actually have those attributes as proper activity fields, so `activity.url`, `activity.channel`, `activity.platform`, `activity.body`, etc.

Apart from that, the whole PR looks good to me and ready to be merged! 💪

2022-10-19 13:33 UTC, mariobalca commented on frontend/src/modules/dashboard/components/dashboard-count.vue
> +    computedBageLabel(resultSet) {
Same typo here

2022-10-20 06:53 UTC, gaspergrom commented on frontend/src/modules/dashboard/components/activities/integrations/devto/activities-devto-channel.vue
> +    class="text-red"
yeah was my mistake, correct color is brand-500, so fixed it on all places

2022-10-20 06:54 UTC, gaspergrom commented on frontend/src/modules/dashboard/components/activities/integrations/github/activities-github-channel.vue
> +    :href="activity.attributes.repo"
did it that activity.attributes.repo is fallback if channel is not present so we at least display something

2022-10-20 06:55 UTC, gaspergrom commented on frontend/src/modules/dashboard/components/activities/dashboard-activities-count.vue
> +    computedBageLabel(resultSet) {
fixed typo thanks for spotting

2022-10-20 07:05 UTC, gaspergrom commented on frontend/src/modules/dashboard/components/activities/integrations/devto/activities-devto-channel.vue
> +    class="text-red"
i added fallback to all attributes in case we dont have on root element attibutes present we got fallback for it

2022-10-20 10:40 UTC, merged